version: "3"
services:
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    networks:
      - network
networks:
  network:
    driver: bridge
